---
builds:
  - id: mailwhale-builds
    binary: mailwhale
    dir: .
before:
  hooks:
  - sudo npm install -g yarn
  - yarn --cwd webui
  - yarn --cwd webui build
  - cp config.default.yml config.yml
archives:
  - id: mailwhale-archives
    builds:
      - mailwhale-builds
    files:
      - LICENSE
      - README.md
      - webui/public/*
      - config.yml
      - templates/*
      - version.txt
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
dockers:
  - ids:
      - mailwhale-builds
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile-goreleaser
    extra_files:
      - "version.txt"
      - "config.yml"
      - "LICENSE"
      - "README.md"
      - "templates/"
      - "webui/"

    image_templates:
      - "ghcr.io/{{ .Env.GHCR_OWNER }}/mailwhale:latest"
      - "ghcr.io/{{ .Env.GHCR_OWNER }}/mailwhale:{{ .Tag }}"
release:
  mode: replace
